import Control.Exception as E; no = E.catch